In [1]:
from sklearn.base import BaseEstimator

In [9]:
class MyDummyClassifier(BaseEstimator):
    def fit(self,X,y=None):
        pass
    def predict(self,X):
        pred = np.zeros((X.shape[0],1))
        for i in range(X.shape[0]):
            if X['Sex'].iloc[i]==1: #남자
                pred[i] = 0 #사망
            else:
                pred[i] = 1 #생존
        return pred

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [11]:
def fillna(df):
    df['Age'].fillna(df['Age'].mean(),inplace=True)
    df['Cabin'].fillna('N',inplace=True)
    df['Embarked'].fillna('N',inplace=True)
    df['Fare'].fillna(0,inplace=True)
    return df

def drop_features(df):
    df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)
    return df

def format_features(df):
    df['Cabin'] = df['Cabin'].str[:1]
    features=['Sex','Cabin','Embarked']
    for feature in features:
        le=LabelEncoder()
        le=le.fit(df[feature])
        df[feature]=le.transform(df[feature])
    return df

def tranform_features(df):
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    return df

titanic_df = pd.read_csv('titanic_train.csv')

y_titanic_df = titanic_df['Survived']
X_titanic_df = titanic_df.drop('Survived',axis=1)
X_titanic_df = tranform_features(X_titanic_df)
X_train,X_test,y_train,y_test = train_test_split(X_titanic_df,y_titanic_df,test_size=0.2,random_state=0)

myclf = MyDummyClassifier()
myclf.fit(X_train,y_train)
pred = myclf.predict(X_test)
accuracy_score(y_test,pred)

0.7877094972067039

In [12]:
from sklearn.datasets import load_digits

In [13]:
class MyFakeClassifier(BaseEstimator):
    def fit(self,X,y):
        pass
    def predict(self,X):
        return np.zeros((len(X),1),dtype=bool)

In [14]:
digits = load_digits()

In [15]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [16]:
y = (digits.target==7).astype(int)

In [17]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
X_train,X_test,y_train,y_test=train_test_split(digits.data,y,random_state=11)

In [19]:
y_test.shape

(450,)

In [20]:
pd.Series(y_test).value_counts()

0    405
1     45
dtype: int64

In [21]:
fakeclf = MyFakeClassifier()
fakeclf.fit(X_train,y_train)
pred = fakeclf.predict(X_test)
accuracy_score(y_test,pred)

0.9

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
confusion_matrix(y_test,pred)

array([[405,   0],
       [ 45,   0]], dtype=int64)

In [24]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix

In [25]:
def get_clf_eval(y_test,pred):
    confusion = confusion_matrix(y_test,pred)
    accuracy = accuracy_score(y_test,pred)
    precision = precision_score(y_test,pred)
    recall = recall_score(y_test,pred)
    print('오차행렬')
    print(confusion)
    print(f'정확도:{accuracy:.4f} 정밀도:{precision:.4f} 재현율:{recall:.4f}')

In [26]:
titanic_df = pd.read_csv('titanic_train.csv')

y_titanic_df = titanic_df['Survived']
X_titanic_df = titanic_df.drop('Survived',axis=1)
X_titanic_df = tranform_features(X_titanic_df)
X_train,X_test,y_train,y_test = train_test_split(X_titanic_df,y_titanic_df,test_size=0.2,random_state=0)

In [27]:
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(X_train,y_train)
pred=lr_clf.predict(X_test)
get_clf_eval(y_test,pred)

오차행렬
[[92 18]
 [16 53]]
정확도:0.8101 정밀도:0.7465 재현율:0.7681


C:\Users\admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [28]:
fakeclf = MyFakeClassifier()
fakeclf.fit(X_train,y_train)
pred = fakeclf.predict(X_test)
get_clf_eval(y_test,pred)

오차행렬
[[110   0]
 [ 69   0]]
정확도:0.6145 정밀도:0.0000 재현율:0.0000


C:\Users\admin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [30]:
pred_proba = lr_clf.predict_proba(X_test)
pred_proba

array([[0.85127656, 0.14872344],
       [0.89229967, 0.10770033],
       [0.93311939, 0.06688061],
       [0.05349063, 0.94650937],
       [0.31332509, 0.68667491],
       [0.49059842, 0.50940158],
       [0.0822201 , 0.9177799 ],
       [0.06469866, 0.93530134],
       [0.41255002, 0.58744998],
       [0.29149245, 0.70850755],
       [0.91284628, 0.08715372],
       [0.26908456, 0.73091544],
       [0.88018451, 0.11981549],
       [0.09166818, 0.90833182],
       [0.03353731, 0.96646269],
       [0.23062761, 0.76937239],
       [0.86101337, 0.13898663],
       [0.76364171, 0.23635829],
       [0.91228723, 0.08771277],
       [0.63771463, 0.36228537],
       [0.66798355, 0.33201645],
       [0.0532712 , 0.9467288 ],
       [0.88018639, 0.11981361],
       [0.56675265, 0.43324735],
       [0.29665533, 0.70334467],
       [0.1037613 , 0.8962387 ],
       [0.90140969, 0.09859031],
       [0.29727631, 0.70272369],
       [0.16926061, 0.83073939],
       [0.39591645, 0.60408355],
       [0.

In [31]:
pred = lr_clf.predict(X_test)

In [32]:
pred_proba.shape

(179, 2)

In [33]:
pred.shape

(179,)

In [34]:
pred_proba[:3]

array([[0.85127656, 0.14872344],
       [0.89229967, 0.10770033],
       [0.93311939, 0.06688061]])

In [36]:
pred_proba_result = np.concatenate([pred_proba,pred.reshape(-1,1)],axis=1)

In [38]:
pred_proba_result[:5]

array([[0.85127656, 0.14872344, 0.        ],
       [0.89229967, 0.10770033, 0.        ],
       [0.93311939, 0.06688061, 0.        ],
       [0.05349063, 0.94650937, 1.        ],
       [0.31332509, 0.68667491, 1.        ]])

In [39]:
from sklearn.preprocessing import Binarizer

In [41]:
X = [[1,-1,2],
     [2,0,0],
     [0,1.1,1.2]]
binarizer = Binarizer(threshold=1.1)
binarizer.fit_transform(X)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [46]:
custom_threshold = 0.5
pred_proba_1 = pred_proba[:,1].reshape(-1,1)
custom_predict = Binarizer(threshold=custom_threshold).fit_transform(pred_proba_1)

In [47]:
get_clf_eval(y_test,custom_predict)

오차행렬
[[92 18]
 [16 53]]
정확도:0.8101 정밀도:0.7465 재현율:0.7681


In [50]:
custom_threshold = 0.6
pred_proba_1 = pred_proba[:,1].reshape(-1,1)
custom_predict = Binarizer(threshold=custom_threshold).fit_transform(pred_proba_1)
get_clf_eval(y_test,custom_predict)

오차행렬
[[99 11]
 [25 44]]
정확도:0.7989 정밀도:0.8000 재현율:0.6377


In [51]:
custom_threshold = 0.7
pred_proba_1 = pred_proba[:,1].reshape(-1,1)
custom_predict = Binarizer(threshold=custom_threshold).fit_transform(pred_proba_1)
get_clf_eval(y_test,custom_predict)

오차행렬
[[105   5]
 [ 32  37]]
정확도:0.7933 정밀도:0.8810 재현율:0.5362
