In [1]:
from sklearn.datasets import load_iris

In [2]:
iris_data = load_iris()

In [3]:
type(iris_data)

sklearn.utils.Bunch

In [4]:
iris_data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [7]:
iris_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [8]:
iris_data.values()

dict_values([array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
 

In [9]:
iris_data.items()

dict_items([('data', array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4,

In [11]:
type(iris_data.feature_names)

list

In [12]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [13]:
iris = load_iris()
df_clf = DecisionTreeClassifier()
df_clf.fit(iris.data,iris.target)
pred = df_clf.predict(iris.data)
accuracy_score(iris.target,pred)

1.0

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [26]:
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2,
                                                 random_state=121)

In [18]:
X_train

array([[4.6, 3.2, 1.4, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [6.8, 3.2, 5.9, 2.3],
       [6. , 2.2, 4. , 1. ],
       [4.6, 3.1, 1.5, 0.2],
       [6.7, 3.3, 5.7, 2.5],
       [5.6, 2.7, 4.2, 1.3],
       [6.4, 2.9, 4.3, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.4, 3.9, 1.7, 0.4],
       [6.9, 3.2, 5.7, 2.3],
       [6.1, 2.8, 4. , 1.3],
       [5.2, 3.4, 1.4, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [5.7, 4.4, 1.5, 0.4],
       [6.1, 2.9, 4.7, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [6. , 2.2, 5. , 1.5],
       [5.3, 3.7, 1.5, 0.2],
       [6.3, 2.3, 4.4, 1.3],
       [4.9, 3.1, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.8, 3.4, 1.9, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [5.6, 3. , 4.1, 1.3],
       [7.2, 3. , 5.8, 1.6],
       [4.9, 3. , 1.4, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [6.2, 2.8, 4.8, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [6.4, 2.8, 5.6, 2.2],
       [4.9, 2.4, 3.3, 1. ],
       [5.8, 2.7, 5.1, 1.9],
       [6.2, 2.9, 4.3, 1.3],
       [5.8, 2

In [27]:
y_train

array([1, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 2, 2, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 2, 1, 2, 2, 1, 1,
       2, 1, 2, 1, 0, 2, 0, 1, 1, 2, 1, 0, 1, 2, 2, 2, 0, 2, 0, 2, 2, 0,
       0, 2, 0, 1, 2, 2, 0, 2, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 0, 2, 0, 1,
       2, 1, 2, 0, 1, 1, 2, 0, 2, 1, 2, 1, 2, 1, 0, 2, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1])

In [28]:
y_test

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2])

In [29]:
df_clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [31]:
pred = df_clf.predict(X_test)

In [32]:
accuracy_score(y_test,pred)

0.9666666666666667

In [33]:
from sklearn.model_selection import KFold
import numpy as np

In [41]:
iris=load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)
kfold = KFold(n_splits=5,shuffle=True)
cv_accuracy = []
#features.shape
n_iter = 0
for train_index,test_index in kfold.split(features):
#     print(train_index)
#     print(test_index)
    X_train,X_test = features[train_index],features[test_index]
    y_train,y_test = label[train_index],label[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size= X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'{n_iter}회 정확도:{accuracy} 학습데이터크기:{train_size} 검증데이터크기:{test_size}')
    cv_accuracy.append(accuracy)
print(np.mean(cv_accuracy))

1회 정확도:0.9333 학습데이터크기:120 검증데이터크기:30
2회 정확도:0.9 학습데이터크기:120 검증데이터크기:30
3회 정확도:0.9333 학습데이터크기:120 검증데이터크기:30
4회 정확도:0.9667 학습데이터크기:120 검증데이터크기:30
5회 정확도:1.0 학습데이터크기:120 검증데이터크기:30
0.94666


In [42]:
import pandas as pd

In [43]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [44]:
iris_df.head(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [45]:
iris_df['label'] = iris.target

In [46]:
iris_df.head(1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   

   label  
0      0

In [47]:
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [52]:
kfold = KFold(n_splits=3,shuffle=True)
n_iter=0
for train_index,test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(n_iter,'번째')
    print('학습레이블 데이터 분포\n',label_train.value_counts())
    print('검증레이블 데이터 분포\n',label_test.value_counts())

1 번째
학습레이블 데이터 분포
 2    35
1    34
0    31
Name: label, dtype: int64
검증레이블 데이터 분포
 0    19
1    16
2    15
Name: label, dtype: int64
2 번째
학습레이블 데이터 분포
 1    35
0    34
2    31
Name: label, dtype: int64
검증레이블 데이터 분포
 2    19
0    16
1    15
Name: label, dtype: int64
3 번째
학습레이블 데이터 분포
 0    35
2    34
1    31
Name: label, dtype: int64
검증레이블 데이터 분포
 1    19
2    16
0    15
Name: label, dtype: int64


In [54]:
from sklearn.model_selection import StratifiedKFold
kfold = StratifiedKFold(n_splits=3)
n_iter=0
for train_index,test_index in kfold.split(iris_df,iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(n_iter,'번째')
    print('학습레이블 데이터 분포\n',label_train.value_counts())
    print('검증레이블 데이터 분포\n',label_test.value_counts())

1 번째
학습레이블 데이터 분포
 2    34
0    33
1    33
Name: label, dtype: int64
검증레이블 데이터 분포
 0    17
1    17
2    16
Name: label, dtype: int64
2 번째
학습레이블 데이터 분포
 1    34
0    33
2    33
Name: label, dtype: int64
검증레이블 데이터 분포
 0    17
2    17
1    16
Name: label, dtype: int64
3 번째
학습레이블 데이터 분포
 0    34
1    33
2    33
Name: label, dtype: int64
검증레이블 데이터 분포
 1    17
2    17
0    16
Name: label, dtype: int64


In [56]:
iris=load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)
kfold = StratifiedKFold(n_splits=5)
cv_accuracy = []
#features.shape
n_iter = 0
for train_index,test_index in kfold.split(features,label):
#     print(train_index)
#     print(test_index)
    X_train,X_test = features[train_index],features[test_index]
    y_train,y_test = label[train_index],label[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size= X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'{n_iter}회 정확도:{accuracy} 학습데이터크기:{train_size} 검증데이터크기:{test_size}')
    cv_accuracy.append(accuracy)
print(np.mean(cv_accuracy))

1회 정확도:0.9667 학습데이터크기:120 검증데이터크기:30
2회 정확도:0.9667 학습데이터크기:120 검증데이터크기:30
3회 정확도:0.9 학습데이터크기:120 검증데이터크기:30
4회 정확도:0.9667 학습데이터크기:120 검증데이터크기:30
5회 정확도:1.0 학습데이터크기:120 검증데이터크기:30
0.9600200000000001


In [57]:
from sklearn.model_selection import cross_val_score,cross_validate

In [58]:
iris=load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)
scores = cross_val_score(dt_clf,features,label,scoring='accuracy',cv=3)
print(scores)
print(np.round(np.mean(scores),4))      

[0.98 0.94 0.98]
0.9667


In [59]:
grid_parameters = {'max_depth':[1,2,3],
                   'min_samples_split':[2,3]}

In [60]:
from sklearn.model_selection import GridSearchCV

In [65]:
iris= load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2,
                                                 random_state=121)
dtree = DecisionTreeClassifier()
grid_dtree = GridSearchCV(dtree,param_grid=grid_parameters,cv=3,refit=True)
grid_dtree.fit(X_train,y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [66]:
scores_df[['params','mean_test_score','rank_test_score','split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [67]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [68]:
grid_dtree.best_score_

0.975

In [70]:
estimator = grid_dtree.best_estimator_
pred = estimator.predict(X_test)
accuracy_score(y_test,pred)

0.9666666666666667