In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])#1차원 배열

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)#데이터 타입

numpy.ndarray

In [6]:
array1.shape#1차원일 경우 

(5,)

In [7]:
array2=np.array([[1,2,3],[2,3,4]])#2차원 배열

In [8]:
type(array2)

numpy.ndarray

In [9]:
array2.shape

(2, 3)

In [12]:
array3=np.array([[[1,2,3],[2,3,4]],[[1,2,3],[4,5,6]]])

In [13]:
array3.shape#3차원

(2, 2, 3)

In [14]:
array1.ndim#1차원확인

1

In [15]:
array2.ndim#2차원확인

2

In [16]:
array3.ndim#3차원 확인

3

In [17]:
array1.dtype #배열의 형태를 나타낼수 있다.

dtype('int32')

In [3]:
list2=[1,2,'test']
array2 = np.array(list2)

In [4]:
array2#데이터 값이 혼용 되어 있을시 나오는 값

array(['1', '2', 'test'], dtype='<U11')

In [5]:
array2.dtype

dtype('<U11')

In [7]:
array_int = np.array([1,2,3])
array_float =array_int.astype('float64') #데이터 타입을 바꾸겟다.

In [8]:
array_int.dtype

dtype('int32')

In [9]:
array_float.dtype

dtype('float64')

In [10]:
np.arange(10)#1차원

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros((3,3,3),dtype='int32')#기본이 float 형태인데 int로 바꾸엇다.

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [13]:
np.ones((3,3,3),dtype='int32')#배열 안의 값을 1로 채웠다.

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [14]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
array1.reshape(5,2)#데이터의 값가 일치해야한다.갯수가 다 들어가야함.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
array1=array1.reshape(-1,5)

In [22]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
array1.tolist()#리스트 형식으로 뽑아준다.

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [30]:
array1 = np.arange(1,10)

In [27]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
array1[2]

3

In [29]:
array1[-2]

9

In [31]:
array2= array1.reshape(3,3)

In [32]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
array2[1,1]

5

In [35]:
array2[1:2,1:2]

array([[5]])

In [36]:
org_array = np.array([3,1,9,5])
org_array

array([3, 1, 9, 5])

In [37]:
np.sort(org_array)#정렬 할 수 있다.

array([1, 3, 5, 9])

In [38]:
org_array

array([3, 1, 9, 5])

In [39]:
org_array.sort()#원본을 sort 하면 정리한 값 이 리턴된다.

In [40]:
org_array

array([1, 3, 5, 9])

In [41]:
np.sort(org_array)[::-1]#역순 정렬

array([9, 5, 3, 1])

In [42]:
org_array = np.array([3,1,9,5])
np.argsort(org_array)

array([1, 0, 3, 2], dtype=int64)

In [43]:
np.argmax(org_array)

2

In [44]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
B

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [47]:
np.dot(A,B) #행렬의 곱

array([[ 58,  64],
       [139, 154]])

In [48]:
np.dot(B,A) # 행렬의 곱

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])